spring:
  datasource:
    password: sa
    url: jdbc:h2:mem:testedb
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console